version: "3"
services:
    #MySQL Service
    db:
        image: mysql:latest
        container_name: meysametammar_lib-db
        restart: always
        tty: true
        volumes:
            - ./dbdata:/var/lib/mysql
        env_file:
            - ./mysql.env
        networks:
            - meysametammar_library_network

    redis:
        image: "redis:alpine"
        volumes:
            - "./redisdata:/data"
        networks:
            - meysametammar_library_network

    #PHP Service
    # app:
    #     build:
    #         context: ./library_core
    #         dockerfile: Dockerfile
    #     container_name: meysametammar_lib-app
    #     restart: always
    #     tty: true
    #     env_file:
    #         - ./library_core/.env
    #     volumes:
    #         - ./library_core:/app
    #     working_dir: /app
    #     networks:
    #         - meysametammar_library_network
    #     ports:
    #         - 8000:8000

    app:
        build:
            context: ./library_core/vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: "1000"
        container_name: "meysametammar_lib-app"
        restart: always
        image: sail-8.0/app
        ports:
            - "8080:80"
        environment:
            WWWUSER: "1000"
            LARAVEL_SAIL: 1
        env_file:
            - ./library_core/.env
        volumes:
            - "./library_core:/var/www/html"
        networks:
            - meysametammar_library_network
        depends_on:
            - db
            - redis

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: meysametammar_lib-phpmyadmin
        links:
            - db
        env_file:
            - phpmyadmin.env
        restart: always
        networks:
            - meysametammar_library_network
        ports:
            - 8081:80

    #Nginx Service
    # webserver:
    #     image: nginx:alpine
    #     container_name: meysametammar_lib-webserver
    #     restart: always
    #     tty: true
    #     ports:
    #         - "8040:80"
    #     volumes:
    #         - ./dashboard:/var/www
    #         - ./nginx/conf.d/:/etc/nginx/conf.d/
    #         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #     networks:
    #         - meysametammar_library_network

#Docker Networks
networks:
    meysametammar_library_network:
        driver: bridge
